name: soutrali_deals
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  go_router: ^12.1.3
  http: ^1.1.0
  image_picker: ^1.0.7
  animations: ^2.0.11
  shared_preferences: ^2.3.4
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  timeago: ^3.5.0
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2
  uuid: ^4.2.2
  cinetpay: ^1.0.5
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/categories/
    - assets/images/
    - assets/images/orange_money.png
    - assets/images/mtn_money.png
    - assets/images/moov_money.png
    - assets/avatars/
    - assets/products/
